apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --chart
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: blackbox
  name: blackbox
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: blackbox
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --chart
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: blackbox
    spec:
      containers:
        - image: prom/blackbox-exporter
          name: blackbox
          ports:
            - containerPort: 9115
              protocol: TCP
      restartPolicy: Always
