apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --chart
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: grafana
  name: grafana
spec:
  ports:
    - name: "3000"
      port: {{ .Values.EXTERNAL_PORT }}
      targetPort: 3000
  externalIPs:
    - {{ .Values.EXTERNAL_IP }}
  selector:
    io.kompose.service: grafana
